### ISSUE TITLE
Leaked IntentReceiver

### ISSUE THREAD

**Issue by AdrianLxM** [StephenBlackWasAlreadyTaken/NightWatch#36]
Leaked  IntentReceiver

When changing watchfaces (on current master) I get the following exception.
It doesn't come from the Broadcast/MessageReceiver registered and unregistered in onDestroy().

It doesn't seem to have much influence on the programme. -> low priority?
I just wondered because my own WatchFace showed this exception - but the plain master branch does that too.

############################
06-09 16:47:00.203    6048-6048/com.dexdrip.stephenblack.nightwatch E/ActivityThread﹕ Service com.dexdrip.stephenblack.nightwatch.LargeHome has leaked IntentReceiver android.support.wearable.watchface.WatchFaceService$Engine$1@371daab0 that was originally registered here. Are you missing a call to unregisterReceiver()?
    android.app.IntentReceiverLeaked: Service com.dexdrip.stephenblack.nightwatch.LargeHome has leaked IntentReceiver android.support.wearable.watchface.WatchFaceService$Engine$1@371daab0 that was originally registered here. Are you missing a call to unregisterReceiver()?
            at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:903)
            at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:704)
            at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1643)
            at android.app.ContextImpl.registerReceiver(ContextImpl.java:1623)
            at android.app.ContextImpl.registerReceiver(ContextImpl.java:1617)
            at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:489)
            at android.support.wearable.watchface.WatchFaceService$Engine.dispatchAmbientModeChanged(WatchFaceService.java:429)
            at android.support.wearable.watchface.WatchFaceService$Engine.maybeUpdateAmbientMode(WatchFaceService.java:419)
            at android.support.wearable.watchface.WatchFaceService$Engine.onCommand(WatchFaceService.java:192)
            at android.service.wallpaper.WallpaperService$Engine.doCommand(WallpaperService.java:961)
            at android.service.wallpaper.WallpaperService$IWallpaperEngineWrapper.executeMessage(WallpaperService.java:1175)
            at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:37)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by AdrianLxM** [comment]
(Possible) explanation why this happens:

Every time, a Watchface gets instatiated, it creates a new Engine ([Line 56](https://github.com/ustwo/clockwise/blob/develop/ustwo-clockwise-wearable/src/main/java/com/ustwo/clockwise/WatchFace.java#L56))

Aparently "onCreate()" is called as it registers the Receiver ([Line 281](https://github.com/ustwo/clockwise/blob/develop/ustwo-clockwise-wearable/src/main/java/com/ustwo/clockwise/WatchFace.java#L281)), but "onDestroy()" is not.
